import '../../domain/models/food_item.dart';
import '../../domain/models/meal.dart';
import '../../domain/models/nutrition.dart';
import '../../domain/models/user_profile.dart';
import '../../domain/units.dart';

/// The coach. The AI coach calls Nutriq's own server function, which holds the
/// AI-provider key and applies the same safety rules server-side.
abstract interface class CoachService {
  /// True when replies are scripted rather than generated by a live model.
  bool get isDemo;

  /// Short name shown in the UI (e.g. "Demo coach").
  String get label;

  /// [onPartial] receives the reply so far while it streams in (AI coach only).
  Future<CoachReply> reply({
    required String message,
    required CoachContext context,
    List<ChatMessage> history = const [],
    void Function(String textSoFar)? onPartial,
  });

  /// One short, glanceable line for the Today screen.
  CoachInsight insight(CoachContext context);
}

/// What the coach is allowed to know: the profile and the local log.
class CoachContext {
  const CoachContext({
    required this.profile,
    required this.today,
    required this.todayMealCount,
    required this.recentDays,
    required this.now,
    this.todayMeals = const [],
    this.savedFoods = const [],
    this.units = UnitSystem.metric,
  });

  final UserProfile? profile;
  final NutritionTotals today;
  final int todayMealCount;

  /// Last 7 logical days, oldest first (may be empty).
  final List<DaySummary> recentDays;
  final DateTime now;

  /// Today's meals, oldest first.
  final List<Meal> todayMeals;

  /// "My foods" templates (servings == 1).
  final List<FoodItem> savedFoods;
  final UnitSystem units;

  bool get restricted => profile?.dietingGuidanceRestricted ?? false;
}

class DaySummary {
  const DaySummary({required this.day, required this.totals, required this.mealCount});
  final DateTime day;
  final NutritionTotals totals;
  final int mealCount;
}

enum CoachReplyKind { answer, fallback, safety, medical, prediction }

class CoachReply {
  const CoachReply({required this.text, required this.kind, required this.isDemo, this.notice});
  final String text;
  final CoachReplyKind kind;
  final bool isDemo;

  /// Why this reply isn't a normal one (e.g. offline, so it's scripted).
  final String? notice;
}

class CoachInsight {
  const CoachInsight({required this.text, required this.suggestedPrompt});
  final String text;
  final String suggestedPrompt;
}

enum ChatRole { user, coach }

class ChatMessage {
  const ChatMessage({required this.role, required this.text, this.isDemo = false, this.kind, this.notice});
  final ChatRole role;
  final String text;
  final bool isDemo;
  final CoachReplyKind? kind;
  final String? notice;
}

/// Suggested prompts shown in the coach and on Today.
abstract final class CoachPrompts {
  static const protein = 'How am I doing with my protein today?';
  static const dinner = 'Suggest a balanced dinner for my goal.';
  static const week = 'What can I improve this week?';
  static const strength = 'Help me stay consistent with strength training.';
  static const all = [protein, dinner, week, strength];
}
