import '../../domain/models/nutrition.dart';
import '../../domain/models/user_profile.dart';

/// The coach. A real implementation should call **your own backend**, which
/// holds any AI-provider key and applies the same safety rules server-side.
abstract interface class CoachService {
  /// True when replies are scripted rather than generated by a live model.
  bool get isDemo;

  /// Short name shown in the UI (e.g. "Demo coach").
  String get label;

  Future<CoachReply> reply({
    required String message,
    required CoachContext context,
    List<ChatMessage> history = const [],
  });

  /// One short, glanceable line for the Today screen.
  CoachInsight insight(CoachContext context);
}

/// What the coach is allowed to know: the profile and the local log.
class CoachContext {
  const CoachContext({
    required this.profile,
    required this.today,
    required this.todayMealCount,
    required this.recentDays,
    required this.now,
  });

  final UserProfile? profile;
  final NutritionTotals today;
  final int todayMealCount;

  /// Last 7 logical days, oldest first (may be empty).
  final List<DaySummary> recentDays;
  final DateTime now;

  bool get restricted => profile?.dietingGuidanceRestricted ?? false;
}

class DaySummary {
  const DaySummary({required this.day, required this.totals, required this.mealCount});
  final DateTime day;
  final NutritionTotals totals;
  final int mealCount;
}

enum CoachReplyKind { answer, fallback, safety, medical, prediction }

class CoachReply {
  const CoachReply({required this.text, required this.kind, required this.isDemo});
  final String text;
  final CoachReplyKind kind;
  final bool isDemo;
}

class CoachInsight {
  const CoachInsight({required this.text, required this.suggestedPrompt});
  final String text;
  final String suggestedPrompt;
}

enum ChatRole { user, coach }

class ChatMessage {
  const ChatMessage({required this.role, required this.text, this.isDemo = false, this.kind});
  final ChatRole role;
  final String text;
  final bool isDemo;
  final CoachReplyKind? kind;
}

/// Suggested prompts shown in the coach and on Today.
abstract final class CoachPrompts {
  static const protein = 'How am I doing with my protein today?';
  static const dinner = 'Suggest a balanced dinner for my goal.';
  static const week = 'What can I improve this week?';
  static const strength = 'Help me stay consistent with strength training.';
  static const all = [protein, dinner, week, strength];
}
