import 'ids.dart';
import 'models/food_item.dart';

/// A named amount of a food, in grams (or millilitres for drinks).
class Portion {
  const Portion(this.label, this.grams);
  final String label;
  final double grams;
}

/// One food in Nutriq's built-in list. Values are typical references per
/// 100 g (or 100 ml for drinks) — estimates, not measurements of a meal.
class CatalogFood {
  const CatalogFood(
    this.name,
    this.kcal,
    this.protein,
    this.carbs,
    this.fat, {
    required this.defaultUnit,
    required this.portions,
    this.aliases = const [],
    this.brands = const {},
    this.liquid = false,
    this.containsAlcohol = false,
  });

  final String name;
  final double kcal;
  final double protein;
  final double carbs;
  final double fat;

  /// Unit used when none is given (a key of [portions]).
  final String defaultUnit;
  final Map<String, Portion> portions;

  /// Other names people use (lowercase).
  final List<String> aliases;

  /// Brand name (lowercase) → name shown on the logged food.
  final Map<String, String> brands;
  final bool liquid;

  /// Alcohol has 7 kcal/g, so its calories don't match the macros.
  final bool containsAlcohol;

  /// This food as a meal ingredient. [unit] is a key of [portions], or `g` /
  /// `ml` with [quantity] in grams/millilitres; other units use the default.
  FoodItem item({double quantity = 1, String? unit, String? brand}) {
    final shownName = brand == null ? name : brands[brand] ?? name;
    if (unit == 'g' || unit == 'ml') {
      return _make(shownName, servings: 1, label: '${_amount(quantity)} $unit', grams: quantity);
    }
    final portion = portions[unit] ?? portions[defaultUnit]!;
    return _make(
      shownName,
      servings: quantity,
      label: '${portion.label} (${_amount(portion.grams)} ${liquid ? 'ml' : 'g'})',
      grams: portion.grams,
    );
  }

  FoodItem _make(String shownName, {required double servings, required String label, required double grams}) {
    double per(double per100) => (per100 * grams / 100 * 10).round() / 10;
    return FoodItem(
      id: newId(),
      name: shownName,
      servings: servings,
      servingLabel: label,
      caloriesPerServing: per(kcal),
      proteinPerServing: per(protein),
      carbsPerServing: per(carbs),
      fatPerServing: per(fat),
    );
  }

  static String _amount(double v) => v == v.roundToDouble() ? '${v.round()}' : v.toStringAsFixed(1);
}

/// Nutriq's built-in list of everyday foods, used to turn "2 cups of rice"
/// into numbers without any AI. Includes many Filipino staples.
abstract final class FoodCatalog {
  static final List<CatalogFood> foods = _foods;

  static final Map<String, CatalogFood> _byAlias = {
    for (final f in _foods)
      for (final a in [f.name.toLowerCase(), ...f.aliases, ...f.brands.keys]) a: f,
  };

  /// The food with this name, alias or brand (lowercase), if any.
  static CatalogFood? byAlias(String alias) => _byAlias[alias.toLowerCase().trim()];

  /// Foods matching [query], best first: exact name, then names starting with
  /// it, then a word starting with it, then containing it.
  static List<CatalogFood> search(String query, {int limit = 8}) {
    final q = query.toLowerCase().trim();
    if (q.isEmpty) return const [];
    int? score(CatalogFood f) {
      int? best;
      for (final term in [f.name.toLowerCase(), ...f.aliases, ...f.brands.keys]) {
        final s = term == q
            ? 0
            : term.startsWith(q)
            ? 1
            : term.split(RegExp(r'[\s,()/-]+')).any((w) => w.startsWith(q))
            ? 2
            : term.contains(q)
            ? 3
            : null;
        if (s != null && (best == null || s < best)) best = s;
      }
      return best;
    }

    final scored = [
      for (final f in _foods)
        if (score(f) case final s?) (food: f, score: s),
    ]..sort((a, b) => a.score != b.score ? a.score - b.score : a.food.name.length - b.food.name.length);
    return [for (final s in scored.take(limit)) s.food];
  }
}

const _cup = 'cup';
const _piece = 'piece';
const _serving = 'serving';

Map<String, Portion> _p(Map<String, (String, double)> m) => {
  for (final e in m.entries) e.key: Portion(e.value.$1, e.value.$2),
};

final List<CatalogFood> _foods = [
  // ── Rice, grains, bread, noodles ──────────────────────────────────────────
  CatalogFood(
    'White rice, cooked',
    130,
    2.7,
    28.2,
    0.3,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup cooked', 158), 'bowl': ('1 bowl', 240), 'plate': ('1 plate', 240)}),
    aliases: ['rice', 'white rice', 'steamed rice', 'plain rice', 'cooked rice', 'jasmine rice', 'kanin'],
  ),
  CatalogFood(
    'Brown rice, cooked',
    112,
    2.3,
    23.5,
    0.8,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup cooked', 195)}),
    aliases: ['brown rice'],
  ),
  CatalogFood(
    'Garlic fried rice (sinangag)',
    165,
    3,
    29,
    4,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 160), 'plate': ('1 plate', 240), 'bowl': ('1 bowl', 240)}),
    aliases: ['garlic rice', 'garlic fried rice', 'sinangag'],
  ),
  CatalogFood(
    'Fried rice',
    170,
    5,
    25,
    5.5,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 160), 'plate': ('1 plate', 240), 'bowl': ('1 bowl', 240)}),
    aliases: ['fried rice', 'egg fried rice', 'yang chow', 'yangchow'],
  ),
  CatalogFood(
    'Oatmeal, cooked',
    71,
    2.5,
    12,
    1.5,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 234), 'bowl': ('1 bowl', 234)}),
    aliases: ['oatmeal', 'cooked oats', 'porridge'],
  ),
  CatalogFood(
    'Rolled oats, dry',
    379,
    13,
    68,
    6.5,
    defaultUnit: _serving,
    portions: _p({'serving': ('½ cup dry', 40), 'cup': ('1 cup dry', 80)}),
    aliases: ['oats', 'rolled oats', 'dry oats', 'quaker oats'],
  ),
  CatalogFood(
    'Corn flakes cereal',
    357,
    7.5,
    84,
    0.4,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 28), 'bowl': ('1 bowl', 40)}),
    aliases: ['cereal', 'corn flakes', 'cornflakes'],
  ),
  CatalogFood(
    'Pandesal',
    290,
    9,
    52,
    5,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 piece', 35)}),
    aliases: ['pandesal', 'pan de sal', 'bread roll'],
  ),
  CatalogFood(
    'White bread',
    265,
    9,
    49,
    3.2,
    defaultUnit: 'slice',
    portions: _p({'slice': ('1 slice', 28)}),
    aliases: ['bread', 'white bread', 'loaf bread', 'sliced bread', 'toast'],
    brands: {'gardenia': 'Gardenia white bread', 'gardenia bread': 'Gardenia white bread'},
  ),
  CatalogFood(
    'Whole wheat bread',
    250,
    12.5,
    43,
    3.5,
    defaultUnit: 'slice',
    portions: _p({'slice': ('1 slice', 32)}),
    aliases: ['wheat bread', 'whole wheat bread', 'brown bread', 'whole grain bread'],
  ),
  CatalogFood(
    'Pasta, cooked',
    158,
    5.8,
    31,
    0.9,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 140), 'plate': ('1 plate', 280)}),
    aliases: ['pasta', 'plain pasta', 'macaroni', 'penne'],
  ),
  CatalogFood(
    'Spaghetti with meat sauce',
    140,
    5.5,
    20,
    4,
    defaultUnit: 'plate',
    portions: _p({'plate': ('1 plate', 250), 'cup': ('1 cup', 140)}),
    aliases: ['spaghetti', 'filipino spaghetti', 'sweet spaghetti', 'spaghetti bolognese'],
    brands: {'jollibee spaghetti': 'Jollibee Spaghetti'},
  ),
  CatalogFood(
    'Macaroni and cheese',
    164,
    7,
    19,
    6.6,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 200)}),
    aliases: ['mac and cheese', 'mac n cheese', 'macaroni and cheese'],
  ),
  CatalogFood(
    'Instant pancit canton',
    483,
    10,
    62,
    23,
    defaultUnit: 'pack',
    portions: _p({'pack': ('1 pack', 60)}),
    aliases: ['pancit canton', 'instant pancit canton', 'canton'],
    brands: {'lucky me pancit canton': 'Lucky Me! Pancit Canton'},
  ),
  CatalogFood(
    'Instant noodle soup',
    440,
    9,
    60,
    18,
    defaultUnit: 'pack',
    portions: _p({'pack': ('1 pack', 55)}),
    aliases: ['instant noodles', 'instant noodle', 'ramen', 'noodle soup', 'cup noodles', 'cup noodle'],
    brands: {'lucky me': 'Lucky Me! instant noodles', 'nissin': 'Nissin instant noodles'},
  ),
  CatalogFood(
    'Pancit bihon',
    150,
    6,
    22,
    4,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 150), 'plate': ('1 plate', 250)}),
    aliases: ['pancit', 'pansit', 'bihon', 'pancit bihon'],
  ),
  CatalogFood(
    'Arroz caldo (lugaw)',
    70,
    3.5,
    10,
    1.5,
    defaultUnit: 'bowl',
    portions: _p({'bowl': ('1 bowl', 350), 'cup': ('1 cup', 240)}),
    aliases: ['arroz caldo', 'lugaw', 'goto', 'congee', 'rice porridge'],
  ),
  CatalogFood(
    'Champorado',
    120,
    2.5,
    24,
    1.5,
    defaultUnit: 'bowl',
    portions: _p({'bowl': ('1 bowl', 250), 'cup': ('1 cup', 240)}),
    aliases: ['champorado', 'chocolate rice porridge'],
  ),
  CatalogFood(
    'Pancake',
    227,
    6.4,
    28,
    10,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 pancake (6 in)', 77)}),
    aliases: ['pancake', 'hotcake'],
  ),
  CatalogFood(
    'Waffle',
    291,
    7.9,
    33,
    14,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 waffle', 75)}),
    aliases: ['waffle'],
  ),

  // ── Eggs, meat, fish ──────────────────────────────────────────────────────
  CatalogFood(
    'Egg, fried',
    196,
    13.6,
    0.8,
    14.8,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 large egg', 46)}),
    aliases: ['egg', 'fried egg', 'sunny side up', 'sunny side up egg', 'itlog'],
  ),
  CatalogFood(
    'Egg, boiled',
    155,
    12.6,
    1.1,
    10.6,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 large egg', 50)}),
    aliases: ['boiled egg', 'hard boiled egg', 'hard-boiled egg', 'nilagang itlog'],
  ),
  CatalogFood(
    'Scrambled eggs',
    149,
    10,
    1.6,
    11,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 egg', 61), 'cup': ('1 cup', 220)}),
    aliases: ['scrambled egg', 'omelette', 'omelet', 'torta'],
  ),
  CatalogFood(
    'Tuna flakes in oil, canned',
    198,
    29.1,
    0,
    8.2,
    defaultUnit: 'can',
    portions: _p({'can': ('1 can, drained', 130), 'tbsp': ('1 tbsp', 15)}),
    aliases: ['tuna', 'canned tuna', 'tinned tuna', 'tuna flakes', 'tuna in oil', 'tuna flakes in oil'],
    brands: {
      'century tuna': 'Century Tuna flakes in oil',
      'century tuna flakes': 'Century Tuna flakes in oil',
      'century tuna hot and spicy': 'Century Tuna hot & spicy',
    },
  ),
  CatalogFood(
    'Tuna in water, canned',
    116,
    25.5,
    0,
    0.8,
    defaultUnit: 'can',
    portions: _p({'can': ('1 can, drained', 130)}),
    aliases: ['tuna in water', 'tuna in brine', 'tuna in spring water'],
  ),
  CatalogFood(
    'Sardines in tomato sauce',
    186,
    20.9,
    0.5,
    10.5,
    defaultUnit: 'can',
    portions: _p({'can': ('1 can', 155)}),
    aliases: ['sardines', 'sardine', 'sardines in tomato sauce'],
    brands: {'ligo': 'Ligo sardines', 'ligo sardines': 'Ligo sardines', '555 sardines': '555 sardines'},
  ),
  CatalogFood(
    'Corned beef, canned',
    250,
    27,
    0.5,
    15,
    defaultUnit: _serving,
    portions: _p({'serving': ('⅓ can', 85), 'can': ('1 can', 150)}),
    aliases: ['corned beef', 'corn beef'],
    brands: {'argentina corned beef': 'Argentina corned beef', 'purefoods corned beef': 'Purefoods corned beef'},
  ),
  CatalogFood(
    'Luncheon meat',
    315,
    13,
    4.6,
    27,
    defaultUnit: 'slice',
    portions: _p({'slice': ('1 slice', 40), 'can': ('1 can', 340)}),
    aliases: ['luncheon meat', 'spam', 'luncheon'],
  ),
  CatalogFood(
    'Hotdog',
    290,
    10,
    4,
    26,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 hotdog', 45)}),
    aliases: ['hotdog', 'hot dog', 'frankfurter', 'sausage'],
  ),
  CatalogFood(
    'Longganisa',
    330,
    14,
    12,
    25,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 piece', 40)}),
    aliases: ['longganisa', 'longanisa', 'longaniza', 'skinless longganisa'],
  ),
  CatalogFood(
    'Tocino',
    260,
    15,
    18,
    14,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 serving', 100), 'piece': ('1 slice', 30)}),
    aliases: ['tocino', 'pork tocino', 'chicken tocino'],
  ),
  CatalogFood(
    'Beef tapa',
    220,
    25,
    5,
    11,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 serving', 100)}),
    aliases: ['tapa', 'beef tapa'],
  ),
  CatalogFood(
    'Tapsilog',
    188,
    11.8,
    16.9,
    7.9,
    defaultUnit: 'plate',
    portions: _p({'plate': ('1 plate (tapa, garlic rice, egg)', 306)}),
    aliases: ['tapsilog'],
  ),
  CatalogFood(
    'Longsilog',
    230,
    8.6,
    18.8,
    13.3,
    defaultUnit: 'plate',
    portions: _p({'plate': ('1 plate (3 longganisa, garlic rice, egg)', 326)}),
    aliases: ['longsilog'],
  ),
  CatalogFood(
    'Tocilog',
    201,
    8.5,
    21.2,
    8.9,
    defaultUnit: 'plate',
    portions: _p({'plate': ('1 plate (tocino, garlic rice, egg)', 306)}),
    aliases: ['tocilog'],
  ),
  CatalogFood(
    'Chicken breast, cooked',
    165,
    31,
    0,
    3.6,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 fillet', 150), 'serving': ('1 serving', 100)}),
    aliases: ['chicken', 'chicken breast', 'grilled chicken', 'grilled chicken breast', 'chicken fillet'],
  ),
  CatalogFood(
    'Fried chicken',
    268,
    22,
    8,
    16,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 piece', 120)}),
    aliases: ['fried chicken'],
    brands: {'chickenjoy': 'Jollibee Chickenjoy', 'chicken joy': 'Jollibee Chickenjoy'},
  ),
  CatalogFood(
    'Chicken adobo',
    200,
    18,
    2,
    13,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 serving', 150), 'cup': ('1 cup', 150), 'piece': ('1 piece', 90)}),
    aliases: ['adobo', 'chicken adobo', 'adobong manok'],
  ),
  CatalogFood(
    'Pork adobo',
    290,
    17,
    2,
    24,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 serving', 150), 'cup': ('1 cup', 150)}),
    aliases: ['pork adobo', 'adobong baboy'],
  ),
  CatalogFood(
    'Chicken inasal',
    210,
    25,
    2,
    11,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 leg quarter', 180)}),
    aliases: ['inasal', 'chicken inasal'],
  ),
  CatalogFood(
    'Lechon kawali (crispy pork belly)',
    520,
    9,
    0,
    53,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 serving', 100)}),
    aliases: ['lechon kawali', 'crispy pork belly', 'bagnet'],
  ),
  CatalogFood(
    'Roast pork (lechon)',
    330,
    25,
    0,
    25,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 serving', 100)}),
    aliases: ['lechon', 'roast pork', 'lechon baboy'],
  ),
  CatalogFood(
    'Pork chop, fried',
    230,
    26,
    0,
    14,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 chop', 140)}),
    aliases: ['pork', 'pork chop', 'porkchop', 'fried pork chop'],
  ),
  CatalogFood(
    'Ground beef, cooked',
    250,
    26,
    0,
    15.4,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 serving', 100), 'cup': ('1 cup', 140)}),
    aliases: ['ground beef', 'minced beef', 'beef mince', 'giniling'],
  ),
  CatalogFood(
    'Beef steak',
    220,
    27,
    0,
    12,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 steak', 170), 'serving': ('1 serving', 100)}),
    aliases: ['beef', 'steak', 'beef steak', 'sirloin', 'ribeye', 'bistek'],
  ),
  CatalogFood(
    'Salmon, cooked',
    206,
    22,
    0,
    12.4,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 fillet', 140)}),
    aliases: ['salmon', 'salmon fillet', 'grilled salmon'],
  ),
  CatalogFood(
    'Tilapia, fried',
    190,
    24,
    0,
    10,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 fish', 130)}),
    aliases: ['fish', 'tilapia', 'fried tilapia', 'fried fish', 'pritong isda'],
  ),
  CatalogFood(
    'Milkfish (bangus), fried',
    200,
    22,
    0,
    12,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 serving', 120)}),
    aliases: ['bangus', 'milkfish', 'daing na bangus', 'fried bangus'],
  ),
  CatalogFood(
    'Dried fish (tuyo, daing)',
    300,
    50,
    0,
    11,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 piece', 10)}),
    aliases: ['tuyo', 'daing', 'dried fish'],
  ),
  CatalogFood(
    'Shrimp, cooked',
    99,
    24,
    0.2,
    0.3,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 serving', 100)}),
    aliases: ['shrimp', 'prawn', 'prawns', 'hipon'],
  ),
  CatalogFood(
    'Tofu (tokwa), firm',
    144,
    17,
    3,
    8.7,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 serving', 100)}),
    aliases: ['tofu', 'tokwa', 'bean curd'],
  ),
  CatalogFood(
    'Bacon',
    541,
    37,
    1.4,
    42,
    defaultUnit: 'slice',
    portions: _p({'slice': ('1 slice', 8)}),
    aliases: ['bacon'],
  ),
  CatalogFood(
    'Ham',
    145,
    21,
    1.5,
    5.5,
    defaultUnit: 'slice',
    portions: _p({'slice': ('1 slice', 28)}),
    aliases: ['ham', 'ham slice'],
  ),
  CatalogFood(
    'Pork and beans, canned',
    106,
    5.2,
    20,
    1.6,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 250), 'can': ('1 can', 230)}),
    aliases: ['pork and beans', 'pork n beans'],
  ),

  // ── Filipino dishes and snacks ────────────────────────────────────────────
  CatalogFood(
    'Pork sinigang',
    62,
    5,
    2.5,
    3.5,
    defaultUnit: 'bowl',
    portions: _p({'bowl': ('1 bowl', 350), 'cup': ('1 cup', 240)}),
    aliases: ['sinigang', 'pork sinigang', 'sinigang na baboy'],
  ),
  CatalogFood(
    'Chicken tinola',
    55,
    6,
    2,
    2.5,
    defaultUnit: 'bowl',
    portions: _p({'bowl': ('1 bowl', 350), 'cup': ('1 cup', 240)}),
    aliases: ['tinola', 'chicken tinola'],
  ),
  CatalogFood(
    'Bulalo (beef soup)',
    80,
    7,
    2,
    5,
    defaultUnit: 'bowl',
    portions: _p({'bowl': ('1 bowl', 400), 'cup': ('1 cup', 240)}),
    aliases: ['bulalo', 'nilaga', 'beef nilaga', 'beef soup'],
  ),
  CatalogFood(
    'Kare-kare',
    190,
    12,
    5,
    14,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 serving', 200), 'cup': ('1 cup', 200)}),
    aliases: ['kare-kare', 'kare kare', 'karekare'],
  ),
  CatalogFood(
    'Menudo / afritada / caldereta',
    160,
    12,
    7,
    9,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 serving', 200), 'cup': ('1 cup', 200)}),
    aliases: ['menudo', 'afritada', 'caldereta', 'kaldereta', 'mechado', 'pork menudo'],
  ),
  CatalogFood(
    'Chopsuey (stir-fried vegetables)',
    70,
    3,
    7,
    3.5,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 150)}),
    aliases: [
      'chopsuey',
      'chop suey',
      'stir fried vegetables',
      'stir-fried vegetables',
      'mixed vegetables',
      'vegetables',
      'veggies',
      'gulay',
    ],
  ),
  CatalogFood(
    'Pinakbet',
    80,
    3,
    7,
    5,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 150)}),
    aliases: ['pinakbet', 'pakbet'],
  ),
  CatalogFood(
    'Siomai',
    200,
    11,
    15,
    11,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 piece', 25)}),
    aliases: ['siomai', 'shumai', 'dumpling', 'gyoza', 'wonton'],
  ),
  CatalogFood(
    'Siopao (asado)',
    250,
    9,
    38,
    7,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 piece', 120)}),
    aliases: ['siopao', 'steamed bun', 'pork bun'],
  ),
  CatalogFood(
    'Lumpia shanghai',
    300,
    12,
    20,
    19,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 piece', 20)}),
    aliases: ['lumpia', 'lumpiang shanghai', 'lumpia shanghai', 'spring roll', 'egg roll'],
  ),
  CatalogFood(
    'Fishball',
    200,
    8,
    25,
    8,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 piece', 10), 'stick': ('1 stick (5 pieces)', 50)}),
    aliases: ['fishball', 'fish ball'],
  ),
  CatalogFood(
    'Banana cue',
    230,
    1,
    45,
    6,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 stick', 120)}),
    aliases: ['banana cue', 'bananacue', 'banana q'],
  ),
  CatalogFood(
    'Turon',
    290,
    2,
    45,
    11,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 piece', 70)}),
    aliases: ['turon', 'banana lumpia', 'banana spring roll'],
  ),
  CatalogFood(
    'Ensaymada',
    410,
    8,
    50,
    20,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 piece', 70)}),
    aliases: ['ensaymada', 'ensaimada'],
  ),
  CatalogFood(
    'Puto',
    210,
    4,
    44,
    2,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 piece', 30)}),
    aliases: ['puto', 'rice cake'],
  ),
  CatalogFood(
    'Halo-halo',
    120,
    2,
    22,
    3,
    defaultUnit: 'glass',
    portions: _p({'glass': ('1 glass', 300)}),
    aliases: ['halo-halo', 'halo halo', 'halohalo'],
  ),
  CatalogFood(
    'Leche flan',
    240,
    6,
    35,
    8,
    defaultUnit: 'slice',
    portions: _p({'slice': ('1 slice', 80)}),
    aliases: ['leche flan', 'flan', 'custard'],
  ),
  CatalogFood('Taho', 75, 3, 13, 1.2, defaultUnit: _cup, portions: _p({'cup': ('1 cup', 250)}), aliases: ['taho']),

  // ── Fast food and snacks ──────────────────────────────────────────────────
  CatalogFood(
    'Hamburger',
    254,
    13,
    30,
    9,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 burger', 110)}),
    aliases: ['burger', 'hamburger'],
    brands: {'yumburger': 'Jollibee Yumburger'},
  ),
  CatalogFood(
    'French fries',
    312,
    3.4,
    41,
    15,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 regular serving', 100)}),
    aliases: ['fries', 'french fries'],
  ),
  CatalogFood(
    'Pizza',
    266,
    11,
    33,
    10,
    defaultUnit: 'slice',
    portions: _p({'slice': ('1 slice', 107)}),
    aliases: ['pizza', 'pizza slice'],
  ),
  CatalogFood(
    'Chicken nuggets',
    296,
    15,
    16,
    19,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 nugget', 16)}),
    aliases: ['chicken nugget', 'nugget'],
  ),
  CatalogFood(
    'Crackers',
    470,
    10,
    70,
    16,
    defaultUnit: 'pack',
    portions: _p({'pack': ('1 pack', 25)}),
    aliases: ['crackers', 'cracker', 'biscuit'],
    brands: {'skyflakes': 'SkyFlakes crackers', 'sky flakes': 'SkyFlakes crackers'},
  ),
  CatalogFood(
    'Cookies',
    488,
    5,
    64,
    24,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 cookie', 16)}),
    aliases: ['cookie', 'chocolate chip cookie'],
  ),
  CatalogFood(
    'Chocolate bar',
    535,
    7.7,
    59,
    30,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 bar', 45)}),
    aliases: ['chocolate', 'chocolate bar', 'candy bar'],
  ),
  CatalogFood(
    'Ice cream',
    207,
    3.5,
    24,
    11,
    defaultUnit: 'scoop',
    portions: _p({'scoop': ('1 scoop', 66), 'cup': ('1 cup', 132)}),
    aliases: ['ice cream'],
  ),
  CatalogFood(
    'Sandwich (ham and cheese)',
    250,
    13,
    28,
    9,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 sandwich', 150)}),
    aliases: ['sandwich', 'ham sandwich', 'ham and cheese sandwich'],
  ),
  CatalogFood(
    'Burrito',
    210,
    9,
    27,
    7,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 burrito', 220)}),
    aliases: ['burrito'],
  ),
  CatalogFood('Taco', 226, 9, 20, 12, defaultUnit: _piece, portions: _p({'piece': ('1 taco', 80)}), aliases: ['taco']),
  CatalogFood(
    'Sushi',
    145,
    6,
    28,
    1.5,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 piece', 30)}),
    aliases: ['sushi', 'maki', 'california maki', 'sashimi roll'],
  ),
  CatalogFood(
    'Chicken curry',
    150,
    12,
    5,
    9,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 serving', 200), 'cup': ('1 cup', 240)}),
    aliases: ['curry', 'chicken curry'],
  ),
  CatalogFood(
    'Vegetable soup',
    40,
    1.5,
    6,
    1,
    defaultUnit: 'bowl',
    portions: _p({'bowl': ('1 bowl', 350), 'cup': ('1 cup', 240)}),
    aliases: ['soup', 'vegetable soup', 'clear soup'],
  ),
  CatalogFood(
    'Pork barbecue (inihaw)',
    250,
    20,
    10,
    14,
    defaultUnit: 'stick',
    portions: _p({'stick': ('1 stick', 60)}),
    aliases: ['pork barbecue', 'pork bbq', 'bbq', 'barbecue', 'inihaw', 'satay', 'kebab'],
  ),
  CatalogFood(
    'Pork ribs',
    290,
    23,
    3,
    21,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 serving', 150)}),
    aliases: ['ribs', 'pork ribs', 'spareribs', 'baby back ribs'],
  ),
  CatalogFood(
    'Cake',
    370,
    4,
    53,
    16,
    defaultUnit: 'slice',
    portions: _p({'slice': ('1 slice', 80)}),
    aliases: ['cake', 'chocolate cake', 'birthday cake', 'cupcake'],
  ),
  CatalogFood(
    'Donut',
    420,
    5,
    50,
    22,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 donut', 60)}),
    aliases: ['donut', 'doughnut'],
  ),
  CatalogFood(
    'Muffin',
    380,
    5.5,
    52,
    17,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 muffin', 100)}),
    aliases: ['muffin'],
  ),
  CatalogFood(
    'Croissant',
    406,
    8.2,
    45.8,
    21,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 croissant', 57)}),
    aliases: ['croissant'],
  ),
  CatalogFood(
    'Pie',
    265,
    2.4,
    37,
    12,
    defaultUnit: 'slice',
    portions: _p({'slice': ('1 slice', 125)}),
    aliases: ['pie', 'apple pie', 'buko pie'],
  ),
  CatalogFood(
    'Popcorn',
    387,
    13,
    78,
    4.5,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 small bag', 30)}),
    aliases: ['popcorn'],
  ),
  CatalogFood(
    'Peanuts',
    567,
    25.8,
    16,
    49,
    defaultUnit: 'handful',
    portions: _p({'handful': ('1 handful', 28)}),
    aliases: ['peanut', 'peanuts', 'mani'],
  ),
  CatalogFood(
    'Almonds',
    579,
    21,
    22,
    50,
    defaultUnit: 'handful',
    portions: _p({'handful': ('1 handful', 28)}),
    aliases: ['almond', 'almonds'],
  ),

  // ── Fruit and vegetables ──────────────────────────────────────────────────
  CatalogFood(
    'Banana',
    89,
    1.1,
    22.8,
    0.3,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 medium', 118)}),
    aliases: ['banana', 'lakatan', 'latundan'],
  ),
  CatalogFood(
    'Saba banana, boiled',
    120,
    1,
    30,
    0.2,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 piece', 90)}),
    aliases: ['saba', 'saba banana', 'boiled banana', 'nilagang saging'],
  ),
  CatalogFood(
    'Apple',
    52,
    0.3,
    13.8,
    0.2,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 medium', 182)}),
    aliases: ['apple'],
  ),
  CatalogFood(
    'Mango, ripe',
    60,
    0.8,
    15,
    0.4,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 mango (flesh)', 200), 'cup': ('1 cup sliced', 165)}),
    aliases: ['mango', 'ripe mango', 'mangga'],
  ),
  CatalogFood(
    'Orange',
    47,
    0.9,
    11.8,
    0.1,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 medium', 131)}),
    aliases: ['orange', 'dalandan'],
  ),
  CatalogFood(
    'Papaya',
    43,
    0.5,
    11,
    0.3,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 145), 'slice': ('1 slice', 150)}),
    aliases: ['papaya'],
  ),
  CatalogFood(
    'Watermelon',
    30,
    0.6,
    7.6,
    0.2,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 152), 'slice': ('1 wedge', 280)}),
    aliases: ['watermelon', 'pakwan'],
  ),
  CatalogFood(
    'Grapes',
    69,
    0.7,
    18,
    0.2,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 151)}),
    aliases: ['grape', 'grapes'],
  ),
  CatalogFood(
    'Pineapple',
    50,
    0.5,
    13,
    0.1,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 165), 'slice': ('1 slice', 84)}),
    aliases: ['pineapple', 'pinya'],
  ),
  CatalogFood(
    'Strawberries',
    32,
    0.7,
    7.7,
    0.3,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 152)}),
    aliases: ['strawberry', 'strawberries'],
  ),
  CatalogFood(
    'Tomato',
    18,
    0.9,
    3.9,
    0.2,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 medium', 123)}),
    aliases: ['tomato', 'kamatis'],
  ),
  CatalogFood(
    'Cucumber',
    15,
    0.7,
    3.6,
    0.1,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup sliced', 104)}),
    aliases: ['cucumber', 'pipino'],
  ),
  CatalogFood(
    'Carrot',
    41,
    0.9,
    9.6,
    0.2,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 medium', 61)}),
    aliases: ['carrot'],
  ),
  CatalogFood(
    'Avocado',
    160,
    2,
    8.5,
    14.7,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 avocado (flesh)', 150)}),
    aliases: ['avocado', 'abokado'],
  ),
  CatalogFood(
    'Broccoli, cooked',
    35,
    2.4,
    7.2,
    0.4,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 156)}),
    aliases: ['broccoli'],
  ),
  CatalogFood(
    'Green salad (no dressing)',
    15,
    1.2,
    2.9,
    0.2,
    defaultUnit: 'bowl',
    portions: _p({'bowl': ('1 bowl', 150), 'cup': ('1 cup', 55)}),
    aliases: ['salad', 'green salad', 'lettuce'],
  ),
  CatalogFood(
    'Potato, boiled',
    87,
    1.9,
    20,
    0.1,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 medium', 150)}),
    aliases: ['potato', 'boiled potato'],
  ),
  CatalogFood(
    'Sweet potato (kamote), boiled',
    76,
    1.4,
    17.7,
    0.1,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 medium', 130)}),
    aliases: ['sweet potato', 'kamote', 'camote'],
  ),
  CatalogFood(
    'Corn on the cob',
    96,
    3.4,
    21,
    1.5,
    defaultUnit: _piece,
    portions: _p({'piece': ('1 ear', 100)}),
    aliases: ['corn', 'corn on the cob', 'mais'],
  ),

  // ── Dairy, spreads, extras ────────────────────────────────────────────────
  CatalogFood(
    'Butter',
    717,
    0.9,
    0.1,
    81,
    defaultUnit: 'tsp',
    portions: _p({'tsp': ('1 tsp', 5), 'tbsp': ('1 tbsp', 14)}),
    aliases: ['butter', 'margarine'],
  ),
  CatalogFood(
    'Peanut butter',
    588,
    25,
    20,
    50,
    defaultUnit: 'tbsp',
    portions: _p({'tbsp': ('1 tbsp', 16), 'tsp': ('1 tsp', 5)}),
    aliases: ['peanut butter'],
  ),
  CatalogFood(
    'Cheese',
    403,
    25,
    1.3,
    33,
    defaultUnit: 'slice',
    portions: _p({'slice': ('1 slice', 21)}),
    aliases: ['cheese', 'cheddar', 'cheese slice'],
    brands: {'eden cheese': 'Eden cheese', 'eden': 'Eden cheese'},
  ),
  CatalogFood(
    'Yogurt, plain',
    61,
    3.5,
    4.7,
    3.3,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 245)}),
    aliases: ['yogurt', 'yoghurt', 'plain yogurt'],
  ),
  CatalogFood(
    'Greek yogurt, plain nonfat',
    59,
    10.2,
    3.6,
    0.4,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 container', 170)}),
    aliases: ['greek yogurt'],
  ),
  CatalogFood(
    'Protein shake (whey, in water)',
    400,
    80,
    8,
    6,
    defaultUnit: 'scoop',
    portions: _p({'scoop': ('1 scoop', 30)}),
    aliases: ['protein shake', 'whey', 'whey protein', 'protein powder'],
  ),
  CatalogFood(
    'Honey',
    304,
    0.3,
    82,
    0,
    defaultUnit: 'tbsp',
    portions: _p({'tbsp': ('1 tbsp', 21), 'tsp': ('1 tsp', 7)}),
    aliases: ['honey'],
  ),
  CatalogFood(
    'Jam',
    278,
    0.4,
    69,
    0.1,
    defaultUnit: 'tbsp',
    portions: _p({'tbsp': ('1 tbsp', 20)}),
    aliases: ['jam', 'jelly', 'fruit jam'],
  ),
  CatalogFood(
    'Gravy',
    50,
    1.5,
    6,
    2.2,
    defaultUnit: _serving,
    portions: _p({'serving': ('1 serving', 30), 'cup': ('1 cup', 240)}),
    aliases: ['gravy'],
  ),
  CatalogFood(
    'Ketchup',
    112,
    1,
    26,
    0.1,
    defaultUnit: 'tbsp',
    portions: _p({'tbsp': ('1 tbsp', 17)}),
    aliases: ['ketchup', 'catsup', 'banana ketchup'],
  ),
  CatalogFood(
    'Mayonnaise',
    680,
    1,
    0.6,
    75,
    defaultUnit: 'tbsp',
    portions: _p({'tbsp': ('1 tbsp', 14)}),
    aliases: ['mayonnaise', 'mayo'],
  ),
  CatalogFood(
    'Soy sauce',
    53,
    8,
    4.9,
    0.6,
    defaultUnit: 'tbsp',
    portions: _p({'tbsp': ('1 tbsp', 16)}),
    aliases: ['soy sauce', 'toyo'],
  ),
  CatalogFood(
    'Cooking oil',
    884,
    0,
    0,
    100,
    defaultUnit: 'tbsp',
    portions: _p({'tbsp': ('1 tbsp', 14), 'tsp': ('1 tsp', 4.5)}),
    aliases: ['oil', 'cooking oil', 'olive oil', 'vegetable oil', 'coconut oil'],
  ),
  CatalogFood(
    'Condensed milk',
    321,
    7.9,
    54,
    8.7,
    defaultUnit: 'tbsp',
    portions: _p({'tbsp': ('1 tbsp', 19)}),
    aliases: ['condensed milk', 'sweetened condensed milk'],
  ),
  CatalogFood(
    'Sugar',
    387,
    0,
    100,
    0,
    defaultUnit: 'tsp',
    portions: _p({'tsp': ('1 tsp', 4), 'tbsp': ('1 tbsp', 12.5)}),
    aliases: ['sugar'],
  ),

  // ── Drinks ────────────────────────────────────────────────────────────────
  CatalogFood(
    'Milk, whole',
    61,
    3.2,
    4.8,
    3.3,
    defaultUnit: 'glass',
    portions: _p({'glass': ('1 glass', 240), 'cup': ('1 cup', 240)}),
    aliases: ['milk', 'whole milk', 'fresh milk'],
    liquid: true,
  ),
  CatalogFood(
    'Milk, skim',
    34,
    3.4,
    5,
    0.1,
    defaultUnit: 'glass',
    portions: _p({'glass': ('1 glass', 240), 'cup': ('1 cup', 240)}),
    aliases: ['skim milk', 'nonfat milk'],
    liquid: true,
  ),
  CatalogFood(
    'Coffee, black',
    1,
    0.1,
    0,
    0,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 240)}),
    aliases: ['coffee', 'black coffee', 'americano', 'brewed coffee', 'kape'],
    liquid: true,
  ),
  CatalogFood(
    'Coffee with milk',
    45,
    2.3,
    4,
    2.2,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 240)}),
    aliases: ['coffee with milk', 'latte', 'cafe latte', 'white coffee'],
    liquid: true,
  ),
  CatalogFood(
    '3-in-1 coffee',
    430,
    4,
    72,
    14,
    defaultUnit: 'sachet',
    portions: _p({'sachet': ('1 sachet', 20)}),
    aliases: ['3 in 1', '3-in-1', '3in1', '3 in 1 coffee', 'coffee mix', 'instant coffee mix'],
    brands: {'nescafe 3 in 1': 'Nescafé 3-in-1', 'great taste': 'Great Taste 3-in-1'},
  ),
  CatalogFood(
    'Chocolate malt drink (Milo)',
    410,
    8,
    72,
    9,
    defaultUnit: 'sachet',
    portions: _p({'sachet': ('1 sachet (in water)', 22), 'tbsp': ('1 tbsp powder', 8)}),
    aliases: ['milo', 'chocolate drink', 'hot chocolate', 'chocolate malt drink'],
  ),
  CatalogFood(
    'Tea, unsweetened',
    1,
    0,
    0.3,
    0,
    defaultUnit: _cup,
    portions: _p({'cup': ('1 cup', 240)}),
    aliases: ['tea', 'green tea', 'black tea', 'hot tea'],
    liquid: true,
  ),
  CatalogFood(
    'Fruit shake / smoothie',
    70,
    1,
    16,
    0.5,
    defaultUnit: 'glass',
    portions: _p({'glass': ('1 glass', 300)}),
    aliases: ['fruit shake', 'smoothie', 'mango shake', 'shake'],
    liquid: true,
  ),
  CatalogFood(
    'Milkshake',
    110,
    3.5,
    17,
    3.5,
    defaultUnit: 'glass',
    portions: _p({'glass': ('1 glass', 300)}),
    aliases: ['milkshake', 'milk shake'],
    liquid: true,
  ),
  CatalogFood(
    'Orange juice',
    45,
    0.7,
    10.4,
    0.2,
    defaultUnit: 'glass',
    portions: _p({'glass': ('1 glass', 240)}),
    aliases: ['orange juice', 'juice', 'oj'],
    liquid: true,
  ),
  CatalogFood(
    'Soft drink (cola)',
    41,
    0,
    10.6,
    0,
    defaultUnit: 'can',
    portions: _p({'can': ('1 can', 330), 'glass': ('1 glass', 240)}),
    aliases: ['soda', 'coke', 'cola', 'soft drink', 'softdrink', 'softdrinks', 'pepsi', 'sprite', 'royal'],
    liquid: true,
  ),
  CatalogFood(
    'Iced tea, sweetened',
    30,
    0,
    7.5,
    0,
    defaultUnit: 'glass',
    portions: _p({'glass': ('1 glass', 240)}),
    aliases: ['iced tea', 'ice tea', 'nestea'],
    liquid: true,
  ),
  CatalogFood(
    'Beer',
    43,
    0.5,
    3.6,
    0,
    defaultUnit: 'can',
    portions: _p({'can': ('1 can', 330)}),
    aliases: ['beer', 'san miguel', 'san mig', 'red horse', 'pale pilsen'],
    liquid: true,
    containsAlcohol: true,
  ),
  CatalogFood(
    'Water',
    0,
    0,
    0,
    0,
    defaultUnit: 'glass',
    portions: _p({'glass': ('1 glass', 240)}),
    aliases: ['water'],
    liquid: true,
  ),
];
